### ISSUE TITLE
Use eslint instead of jshint for an eslint plugin

### ISSUE THREAD

**Issue by paulfalgout** [aminya/eslint-plugin-yaml#1]
I don't understand how this plugin has anything to do with eslint..

Not only that.. but it sure seems like you're converting the yml to json prior to linting it.. which would seem to defeat the purpose.

**Comment by aminya** [comment]
Thanks. I will look into this. Conslidation/Using with https://github.com/paazmaya/yaml-validator/issues/167 probably would help.
