### ISSUE TITLE
Not on npmjs.com

### ISSUE THREAD

**Issue by matteo-harpoon** [aminya/eslint-plugin-yaml#2]
I cannot seem to be able to run the command `$ npm install eslint-plugin-yaml --save-dev`.

The package doesn't exists on https://www.npmjs.com/package/eslint-plugin-yaml

**Comment by patarapolw** [comment]
Might not be a good idea to install an unmaintained package, but you can install using

```sh
npm install https://github.com/pdehaan/eslint-plugin-yaml.git --save-dev
```

**Comment by aminya** [comment]
Please register this package.

**Comment by pdehaan** [comment]
Oh, sorry, I don't use/maintain this anymore, which is why I never pushed to npm.
If somebody wants to fork/update the codebase and push it to npm and own it, feel free.

**Comment by aminya** [comment]
> 
> 
> Oh, sorry, I don't use/maintain this anymore, which is why I never pushed to npm.
> If somebody wants to fork/update the codebase and push it to npm and own it, feel free.

I can do that if you give me write access to this repository. There is also:
https://github.com/paazmaya/yaml-validator/issues/167
that I think we can consolidate with.

**Comment by aminya** [comment]
This is fixed now.
https://www.npmjs.com/package/eslint-plugin-yaml
