### ISSUE TITLE
Support linting the files inside .github/workflows

### ISSUE THREAD

**Issue by aminya** [aminya/eslint-plugin-yaml#3]
Blocked by https://github.com/eslint/eslint/issues/13418

**Comment by JustFly1984** [comment]
+1
would love to have linting for github actions

**Comment by aminya** [comment]
I opened an issue in the core eslint repository

**Comment by JustFly1984** [comment]
@aminya can you please crosslink issue here?

**Comment by aminya** [comment]
This is available in "0.3.0" now! 


cc: @JustFly1984
